default: &default
  adapter: mysql2
  encoding: utf8mb4
#  host: db
  host: localhost
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bosco_gurin_development

test:
  <<: *default
  database: bosco_gurin_test

